name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: OpenBLAS
      run: homebrew install openblas
      
    - name: configure
      run: ln -s gcc.mak Makefile
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: cd test && ./mk-grid && ../stag < test.inp
      
    - name: Run distcheck
      run: ./cleanup
