name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install-and-cache homebrew tools
      # You may pin to the exact commit or the version.
      # uses: tecoli-com/actions-use-homebrew-tools@8b892d82c1c2194af8c21f09dc45efdbc236bc51
      uses: tecoli-com/actions-use-homebrew-tools@v0.4
      with:
        # 
        tools: 'gcc','openblas'
        # 
        cache: # optional, default is true
        # 
        key: # optional
    
    - name: Configure
      run: ln -s gcc.mak Makefile
      
    - name: Setup path
      run: export PATH=/usr/local/bin:`pwd`:$PATH && echo $PATH
      
    - name: Build 
      run: make FC=gfortran-11 F77=gfortran-11
      
    - name: Run check
      run: cd test && ./mk-grid.sh && ../stag < test.inp
      
    - name: Run distclean
      run: ./cleanup
