name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install-and-cache homebrew tools
      # You may pin to the exact commit or the version.
      # uses: tecoli-com/actions-use-homebrew-tools@8b892d82c1c2194af8c21f09dc45efdbc236bc51
      uses: tecoli-com/actions-use-homebrew-tools@v0.4
      with:
        # 
        tools: openblas
        # 
        cache: # optional, default is true
        # 
        key: # optional
    
    - name: OpenBLAS
      run: homebrew install openblas
      
    - name: configure
      run: ln -s gcc.mak Makefile
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: cd test && ./mk-grid && ../stag < test.inp
      
    - name: Run distcheck
      run: ./cleanup
